Update jenkins_file

diff --git a/jenkins_file b/jenkins_file
--- a/jenkins_file
+++ b/jenkins_file
@@ -1,32 +1,41 @@
-pipeline {
-	agent { label 'master' }
- 
-	stages {
-		stage ('makefile') {
-			steps { 
-				build 'C projects'
-				//*echo 'This is slaveforc node with STAGE 1'
-				//sh 'sleep 10'
+ipeline {
+	agent any
+        stages {
+		stage ('STAGE 1') {
+			steps {
+				sh '''#!/bin/bash
+				git pull https://github.com/riyaz-ahamadm92/C projects.git
+				if [ $? -ne 0 ] ; then
+				git clone https://github.com/riyaz-ahamadm92/C projects.git
+				fi
+				cd C projects
+				make ABC.exe
+				if [ $? -eq 0 ] ; then
+				echo " Build is success "
+				else
+				echo " Build is failed "
+				fi
+				'''
 			}	
 		}
-		stage ('maven') {
+		stage ('STAGE 2') {
 			steps {
-				build 'Java projects'
-				//echo 'This is slaveforjava with STAGE 2'
-				//sh 'sleep 10'
+				sh '''#!/bin/bash
+				git pull https://github.com/riyaz-ahamadm92/java-projects.git
+				if [ $? -ne 0 ] ; then
+				git clone https://github.com/riyaz-ahamadm92/java-projects.git
+				fi
+				cd java-projects
+				mvn clean install
+				if [ $? -eq 0 ] ; then
+				echo " Build is success "
+				else
+				echo " Build is failed "
+				fi
+				'''
 			}	
 		}
-		/*stage ('STAGE 3') {
-			steps {
-				echo 'This is slaveforc with STAGE 3'
-				sh 'sleep 10'
-			}	
-		}
-		stage ('STAGE 4') {
-			steps {
-				echo 'This is master with STAGE 4'
-				sh 'sleep 10'
-			}	
-		}*/
 	}
 }
+
+
